name: absensi_del
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  
  camera: ^0.10.5+9 # Atau versi terbaru
  path_provider: ^2.1.3 # Atau versi terbaru
  path: ^1.8.3 # Atau versi terbaru
  intl: ^0.19.0 # <--- TAMBAHKAN BARIS INI
  image_picker: ^0.8.4+4
  firebase_core: ^2.30.1 # Versi mungkin berbeda, cek pub.dev
  cloud_firestore: ^4.17.3 # Untuk database Firestore
  firebase_auth: ^4.19.5 # Untuk autentikasi (opsional jika tidak pakai auth)
  geolocator: ^10.1.0
  image: ^4.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
