// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyvqlzLQIIvOpiTdHyisxIuEoO24qYbs',
    appId: '1:586457273274:web:e8528908675393dbb10383',
    messagingSenderId: '586457273274',
    projectId: 'absensi-del',
    authDomain: 'absensi-del.firebaseapp.com',
    storageBucket: 'absensi-del.firebasestorage.app',
    measurementId: 'G-EQV2YKR7CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA13Xzg71UQaNWt4fRUQP3j5Hl6E_P1Dns',
    appId: '1:586457273274:android:534d0e2044179c5bb10383',
    messagingSenderId: '586457273274',
    projectId: 'absensi-del',
    storageBucket: 'absensi-del.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3nqPinlBtAPGGDQ081mrxkE30Sbs3Oo',
    appId: '1:586457273274:ios:3ace8a455901e779b10383',
    messagingSenderId: '586457273274',
    projectId: 'absensi-del',
    storageBucket: 'absensi-del.firebasestorage.app',
    iosBundleId: 'com.example.absensiDel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3nqPinlBtAPGGDQ081mrxkE30Sbs3Oo',
    appId: '1:586457273274:ios:3ace8a455901e779b10383',
    messagingSenderId: '586457273274',
    projectId: 'absensi-del',
    storageBucket: 'absensi-del.firebasestorage.app',
    iosBundleId: 'com.example.absensiDel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARyvqlzLQIIvOpiTdHyisxIuEoO24qYbs',
    appId: '1:586457273274:web:36feabdd71eb1940b10383',
    messagingSenderId: '586457273274',
    projectId: 'absensi-del',
    authDomain: 'absensi-del.firebaseapp.com',
    storageBucket: 'absensi-del.firebasestorage.app',
    measurementId: 'G-9V3L9RK941',
  );
}
